config/routes.rb
Topclass::Application.routes.draw do

  get "semesters/new"
  get "semesters/index"
  get "semesters/show"

resources :users
resources :preregister_subjects
resources :sessions, only: [:new, :create, :destroy]
  
root  'sessions#new'
match '/newuser',  to: 'users#new',  via: 'get'
match '/help', to: 'static_pages#help', via: 'get'
match '/about',   to: 'static_pages#about',   via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/new_semester', to: 'new_semester#index', via: 'get'
  match '/new_semester_with_classes', to: 'new_semester#users_in_subject_rule', via: 'get'
  match '/new_semester_with_classes2', to: 'new_semester#users_not_in_subject_rule', via: 'get'
  
  match '/dashboard', to: 'dashboard#show', via: 'get'
  match '/dashboard_charts', to:'dashboard#load_charts', via: 'get' 
  match '/dashboard_notifications', to:'dashboard#notifications', via: 'get' 

  
  match '/forecast', to: 'forecasts#index', via: 'get'  
  match '/forecast_scenario', to: 'forecasts#show', via: 'get'  

resources :subjects
  match '/new_subject',  to: 'subjects#new',  via: 'get'
  match '/list_subject',  to: 'subjects#index',  via: 'get'
  match '/disable', to: 'subjects#disable', :as => 'disable', via: 'get'
  match '/list_student_by', to: 'subjects#showStudentList#:id', via: 'get'
  match '/showStudentList', to: 'subjects#showStudentList', via: 'get'
  match '/config_quota_by', to: 'subjects#goQuotaConfig#:id', via: 'get'
  match '/createQuota', to: 'subjects#createQuota', via: 'post'
  match '/searchStudentList', to: 'subjects#searchStudentList', via: 'get'
  
 
  resources :programs
  match '/list_registered', to: 'programs#showSubjectList#id', via: 'get'
  match '/list_program',  to: 'programs#index',  via: 'get'
  match '/searchSubjectList', to: 'programs#searchSubjectList', via: 'get'
  
  resources :teacher_subjects
  match '/new_teachersubjects',  to: 'teacher_subjects#new',  via: 'get'
  match '/list_teacher_subjects',  to: 'teacher_subjects#index',  via: 'get'

  

end

app/models/teacher_subject.rb
class TeacherSubject < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject
  
  validates :user_id, presence: true
  validates :subject_id, presence: true
  validates :status, presence: true
  
end

app/controllers/teacher_subjects_controller.rb
class TeacherSubjectsController < ApplicationController
  def index
    @teacher_subjects = TeacherSubject.paginate(page: params[:page])
    @teacher_subject = TeacherSubject.new 
  end
  
  def show
    @teacher_subject = TeacherSubject.find(params[:id])
    if @teacher_subject.status == "true" 
      flash[:success] = "TeacherSubject enable"
    else
      flash[:fail] = "TeacherSubject disabled"
    end
  end  
  
  def new
    @subjects = Subject.all
    @teachers = User.where(usertype: 'Profesor')
    @teachersubject = TeacherSubject.new
    @teacher_subject = TeacherSubject.new
  end
  
  def create
    @teacher_subject = TeacherSubject.new(teacher_subject_params)
    @teacher_subject.status = true
    if @teacher_subject.save  
      flash[:success] = "Subject created sucesfull"
      redirect_to teacher_subjects_path
    else
      flash[:fail] = "Fail Subject creation"
      render "new"
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
        @teacher_subject = TeacherSubject.find_by_id(params[:id])
    if @teacher_subject.destroy
      flash[:success] = "teachersubject was destroyed." 
      redirect_to subjects_path
    else
      flash[:fail] = "Fail delete teachersubject"
      render "index"
    end
  end
  
    def teacher_subject_params
      params.require(:teacher_subject).permit(:user_id, :subject_id, :status) 
    end
end

app/controllers/teachersubjects_controller.rb
class TeachersubjectsController < ApplicationController
  def index
    @teachersubjects = TeacherSubject.paginate(page: params[:page])
    @teachersubject = TeacherSubject.new 
  end
  
  def show
    @teachersubject = TeacherSubject.find(params[:id])
    if @teachersubject.status == "true" 
      flash[:success] = "TeacherSubject enable"
    else
      flash[:fail] = "TeacherSubject disabled"
    end
  end  
  
  def new
    @subjects = Subject.all
    @teachers = User.where(usertype: 'Profesor')
    @teachersubject = TeacherSubject.new
  end
  
  def create
    @teachersubject = TeacherSubject.new(teachersubject_params)    
    render teachersubject_params
    if @teachersubject.save  
      flash[:success] = "Subject created sucesfull"
      redirect_to teachersubjects_path
    else
      flash[:fail] = "Fail Subject creation"
      render "new"
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
        @teachersubject = TeacherSubject.find_by_id(params[:id])
    if @teachersubject.destroy
      flash[:success] = "teachersubject was destroyed." 
      redirect_to subjects_path
    else
      flash[:fail] = "Fail delete teachersubject"
      render "index"
    end
  end
  
    def teachersubject_params
      params.require(:teacher_subject).permit(:user_id, :subject_id) 
    end
end

app/helpers/teacher_subjects_helper.rb
module TeacherSubjectsHelper
end

app/views/teacher_subjects/index.html.erb
<% provide(:title, 'Subjects By Teacher') %>
<h1>Subjects By Teacher</h1>
<p align="center"><%= link_to "New Assignation", new_teacher_subject_path, :class => 'btn btn-primary'  %></p> 

<%= will_paginate %>
<ul class="subjects">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Subject Code</th>
      <th>Subject Name</th>
      <th>Teacher Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @teacher_subjects .each do |subject| %>
             <tr>
        <td><%= subject.id %></td>
          <td><%= subject.subject.code %></td>
        <td><%= subject.subject.name %></td>
          <td><%= subject.user.firstname %> <%=subject.user.lastname%></td>
        <td><%= subject.created_at %></td>
        <td>
          
  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</ul>
<%= will_paginate %>

<p align="center"><%= link_to "New Assignation", new_teacher_subject_path, :class => 'btn btn-primary'  %></p> 

app/views/teacher_subjects/new.html.erb
<% provide(:title, 'Create Subject/Teacher') %>
<h1>Create Subject/Teacher Relation</h1>
<div class="row">
  <div class="span6 offset3">

    


    <%= form_for(@teacher_subject) do |f| %>
    
    <%= f.label :subject %>  <%= collection_select(:teacher_subject, :subject_id, Subject.all, :id, :name) %> 
    <%= f.label :teacher %>  <%= collection_select(:teacher_subject, :user_id, User.where(usertype: "Profesor"), :id, :firstname) %>  
     
        <p align="center">
           <%= f.submit "Add new subject", class: "btn btn-primary" %> 
 <%= link_to "Go Back", list_teacher_subjects_path, class: "btn" %> 
     
    </p> 
      
<% end %>

  </div>
</div>