config/routes.rb
Topclass::Application.routes.draw do

  get "semesters/new"
  get "semesters/index"
  get "semesters/show"

resources :users
resources :preregister_subjects
resources :sessions, only: [:new, :create, :destroy]
  
root  'sessions#new'
match '/newuser',  to: 'users#new',  via: 'get'
match '/help', to: 'static_pages#help', via: 'get'
match '/about',   to: 'static_pages#about',   via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/new_semester', to: 'new_semester#index', via: 'get'
  match '/new_semester_with_classes', to: 'new_semester#users_in_subject_rule', via: 'get'
  match '/new_semester_with_classes2', to: 'new_semester#users_not_in_subject_rule', via: 'get'
  
  match '/dashboard', to: 'dashboard#show', via: 'get'
  match '/dashboard_charts', to:'dashboard#load_charts', via: 'get' 
  match '/dashboard_notifications', to:'dashboard#notifications', via: 'get' 

  
  match '/forecast', to: 'forecasts#index', via: 'get'  
  match '/forecast_scenario', to: 'forecasts#show', via: 'get'  

resources :subjects
  match '/new_subject',  to: 'subjects#new',  via: 'get'
  match '/list_subject',  to: 'subjects#index',  via: 'get'
  match '/disable', to: 'subjects#disable', :as => 'disable', via: 'get'
  match '/list_student_by', to: 'subjects#showStudentList#:id', via: 'get'
  match '/showStudentList', to: 'subjects#showStudentList', via: 'get'
  match '/config_quota_by', to: 'subjects#goQuotaConfig#:id', via: 'get'
  match '/createQuota', to: 'subjects#createQuota', via: 'post'
  match '/searchStudentList', to: 'subjects#searchStudentList', via: 'get'
  
 
  resources :programs
  match '/list_registered', to: 'programs#showSubjectList#id', via: 'get'
  match '/list_program',  to: 'programs#index',  via: 'get'
  match '/searchSubjectList', to: 'programs#searchSubjectList', via: 'get'
  
  resources :teacher_subjects
  match '/new_teachersubjects',  to: 'teacher_subjects#new',  via: 'get'
  match '/list_teacher_subjects',  to: 'teacher_subjects#index',  via: 'get'

  

end

app/models/program.rb
class Program < ActiveRecord::Base
  before_save { self.code = code.upcase }
  
  validates :name, presence: true, length: { maximum: 200 }
  validates :code, presence: true, length: { maximum: 100 },  uniqueness: { case_sensitive: false }
  validates :objective, presence: true, length: { maximum: 500 }
  validates :status, presence: true

  has_many :program_semesters
  has_many :semesters, :through => :program_semesters
  
  has_many :user_programs
  has_many :users, :through => :user_programs
  
  has_many :subject_programs
  has_many :subjects, :through => :subject_programs
  
  belongs_to :user

  has_many :preregister_subjects
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    @programs = Program.paginate(page: params[:page])
  end
  
  def showSubjectList
    @program = Program.find(params[:format])
    @semester = Semester.new
    @subject_columns = [   {field: 'idSubject', headerText: 'ID', sortable: true}, {field: 'codeSubject', headerText: 'ID Subject', sortable: true},    
                         {field: 'subjectName', headerText: 'Subject Name', sortable: true},   {field: 'subjectQuota', headerText: 'Quota', sortable: true},   
                        {field: 'preregisterCount', headerText: 'Preinscription', sortable: true}, {field: 'percentaje', headerText: 'Percentaje', sortable: true}                  
                        ] 
    @semester = Semester.last
    @subjects = Program.find_by_sql(["select distinct p.id idProgram, s.id idSubject, s.code codeSubject, s.name subjectName, s.quota subjectQuota, count(ps.id) as preregisterCount, (count(ps.id)*100 / s.quota) percentaje from programs p, subjects s, preregister_subjects ps where p.id = ? and p.id = ps.program_id and ps.subject_id = s.id and ps.semester_id = ? group by ps.subject_id, p.id, s.id, s.code, s.name, s.quota;",  @program.id, @semester.id])
    @semester.status =  @program.id
  end
  
  def searchSubjectList
    @program = Program.find_by_id(params[:semester][:status])
    @semester = Semester.find(params[:semester][:id])
    @subject_columns = [   {field: 'idSubject', headerText: 'ID', sortable: true}, {field: 'codeSubject', headerText: 'ID Subject', sortable: true},    
                         {field: 'subjectName', headerText: 'Subject Name', sortable: true},   {field: 'subjectQuota', headerText: 'Quota', sortable: true},   
                        {field: 'preregisterCount', headerText: 'Preinscription', sortable: true}, {field: 'percentaje', headerText: 'Percentaje', sortable: true}                  
                        ] 
    @subjects = Program.find_by_sql(["select distinct p.id idProgram, s.id idSubject, s.code codeSubject, s.name subjectName, s.quota subjectQuota, count(ps.id) as preregisterCount, (count(ps.id)*100 / s.quota) percentaje from programs p, subjects s, preregister_subjects ps where p.id = ? and p.id = ps.program_id and ps.subject_id = s.id and ps.semester_id = ? group by ps.subject_id, p.id, s.id, s.code, s.name, s.quota;",  @program.id, @semester.id])
    @semester.status =  @program.id
    flash[:success] = "Se ha cargado el listado de materias del programa para el semestre " + @semester.name   
    render "showSubjectList"
  end  
  
  def show
    @program = Program.find(params[:id])
    if @program.status == "true" 
      flash[:success] = "Program enable"
    else
      flash[:fail] = "Program disabled"
    end
  end
  
  def new
    @program = Program.new
  end
  
  def create
    @program = Program.new(program_params)    
    if @program.save  
      flash[:success] = "Program created sucesfull"
      redirect_to programs_path
    else
      flash[:fail] = "Fail Program creation"
      render "new"
    end
  end
  
  def edit
     @program = Program.find(params[:id])
  end
  
  def update
    @program = Program.find_by_id(params[:id])
    if @program.update_attributes(params[:program])
      flash[:success] = "Program was updated"
        redirect_to programs_path
      else
        render "edit"
      end
  end
  
  def destroy
    @program = Program.find_by_id(params[:id])
    if @program.destroy
      flash[:success] = "Program was destroyed."
      redirect_to programs_path
    else
      flash[:fail] = "Fail delete Program"
      render "index"
    end
  end
  
    private

  def program_params
    params.require(:program).permit(:code,:name,:objective,:status) 
    end
  
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_program.html.erb
<li>
  <span class="content"><%= program.name %></span>
  <span class="content"><%= program.code %></span>
  <%if (@user.usertype.eql?("Estudiante") || coordinador?)%>
    <% if !@user.preregister_subjects.where(program_id: program.id).any? %>
      | <%= link_to I18n.t('programas.autoregistro'), preregister_subject_path(:automatic => 1,:user_id =>@user.id,:program_id =>program.id), method: :patch,
        data: { confirm: I18n.t('seguro')} %>
    <% else %>
      | <%= link_to I18n.t('programas.mostrar'), preregister_subject_path(:user_id =>@user.id,:program_id =>program.id), method: :get %>
    <% end %>
    <% if  @user.preregister_subjects.where(program_id: program.id).count < 10 %>
      | <%= link_to I18n.t('programas.preregistrar'), new_preregister_subject_path(:user_id =>@user.id,:program_id =>program.id), method: :get %>
    <% end %>
  <% end %>
</li>

app/views/programs/edit.html.erb
<% provide(:title, 'Editar Subject') %>
<h1>Editar Programa</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@program) do |f| %>
     <%= render 'shared/program_error_messages' %>

    <%= p_fieldset('default',legend: 'Datos Básicos',style: 'margin-bottom:10px') do %>      
    
      <%= f.label :code, "Codigo" %>
      <%= f.text_field :code %>
      
      <%= f.label :name , "Nombre"%>
      <%= f.text_field :name %>
      
      <%= f.label :objective %>
      <%= f.text_area :objective %>
      
      <%= f.label :status , "Estado"%>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   
     
    <% end %> 
    
    <p align="center">
      <%= f.submit "Editar Programa", class: "btn btn-primary" %> 
     <%= link_to "Volver", list_program_path, class: "btn" %> 
    </p> 
      
    <% end %>
  </div>
</div>

app/views/programs/index.html.erb
<% provide(:title, I18n.t('programas.titulo')) %>

<h1><%= I18n.t('programas.titulo') %></h1>
<p align="center"><%= link_to I18n.t('programas.nuevo'), new_program_path, :class => 'btn btn-primary'  %></p>
<%= will_paginate %>
<ul class="programs">
  <table class="table table-striped">
  <thead>
    <tr>
      <th><%= I18n.t('programas.id') %></th>
      <th><%= I18n.t('programas.codigo') %></th>
      <th><%= I18n.t('programas.nombre') %></th>
      <th><%= I18n.t('programas.objetivo') %></th>
      <th><%= I18n.t('programas.acciones') %></th>
    </tr>
  </thead>
  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.id %></td>
          <td><%= program.code %></td>
        <td><%= link_to program.name, program_path(program) %></td>
          <td><%= program.objective %></td>
        <td>
          <%= link_to I18n.t('programas.materias.boton'), list_registered_path(program.id), :class => 'btn btn-mini' %>
          <%= link_to I18n.t('editar'), edit_program_path(program), :class => 'btn btn-mini' %>
          <%= link_to I18n.t('delete'), program_path(program), :method => :delete, :confirm => I18n.t('seguro'), :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</ul>
<%= will_paginate %>
<p align="center"><%= link_to I18n.t('programas.nuevo'), new_program_path, :class => 'btn btn-primary'  %></p>

app/views/programs/new.html.erb
<% provide(:title, 'Create Subject') %>
<h1>Crear Programa</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@program) do |f| %>
     <%= render 'shared/program_error_messages' %>

    <%= p_fieldset('default',legend: 'Datos Básicos',style: 'margin-bottom:10px') do %>      
    
      <%= f.label :code, "Codigo" %>
      <%= f.text_field :code %>
      
      <%= f.label :name , "Nombre"%>
      <%= f.text_field :name %>
      
      <%= f.label :objective %>
      <%= f.text_area :objective %>
      
      <%= f.label :status , "Estado"%>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   
     
    <% end %> 
    
    <p align="center">
      <%= f.submit "Crear Programa", class: "btn btn-primary" %> 
     <%= link_to "Volver", list_program_path, class: "btn" %> 
    </p> 
      
    <% end %>
  </div>
</div>

app/views/programs/show.html.erb
<% provide(:title, 'Create Subject') %>
<h1>Ver Programa</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@program) do |f| %>

    <%= p_fieldset('default',legend: 'Datos Básicos',style: 'margin-bottom:10px') do %>      
    
      <%= f.label :code, "Codigo" %>
      <%= f.text_field :code %>
      
      <%= f.label :name , "Nombre"%>
      <%= f.text_field :name %>
      
      <%= f.label :objective %>
      <%= f.text_area :objective %>
      
      <%= f.label :status , "Estado"%>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   
     
    <% end %> 
    
    <p align="center"> 
     <%= link_to "Volver", list_program_path, class: "btn" %> 
    </p> 
      
    <% end %>
  </div>
</div>

app/views/programs/showSubjectList.html.erb
<script type='text/javascript'>
$(function () {
        $('#container').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Materias por programa'
            },
            subtitle: {
                text: 'Universidad de los Andes'
            },
            xAxis: {
                categories: [
                  <%@subjects.each do |s|%>
                   '<%=s.codeSubject%>',
                  <% end %>
                ]
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'valor'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Cuota',
                data: [
                 <%@subjects.each do |s|%>
                   <%=s.subjectQuota%>,
                  <% end %>
                ]
    
            }, {
                name: 'Preinscritos',
                data: [
                 <%@subjects.each do |s|%>
                   <%=s.preregisterCount%>,
                  <% end %>
                ]
    
            }, {
                name: 'Porcentaje',
                data: [
                  <%@subjects.each do |s|%>
                   <%=s.percentaje%>,
                  <% end %>
                ]
    
            }]
        });
    });

    </script>
<% provide(:title, 'Todas las materias por programa') %>

<h1><%= I18n.t('programas.materias.titulo') %></h1>
<ul class="subjects">
  <%= p_fieldset('default',legend: I18n.t('programas.materias.subtitulo'),style: 'margin-bottom:10px') do %>
       <%= form_for @semester, url: searchSubjectList_path(@semester) , html: {method: "get"} do |f|  %>
  
  <table width="100%">
    <tr>
      <td width="15%">
        <%= f.hidden_field :status %>
      <%= f.label :id , "Semestre"%>
  
      <% semester_array = Semester.all.map { |sem| [sem.name, sem.id] } %>
  
      <%=f.select(:id,options_for_select(semester_array), :style => "width:70px")%>   
      <p align="center"> <%= f.submit "Buscar", class: "btn btn-primary" %>
        <%= link_to I18n.t('programas.materias.volver'), list_program_path, :class => 'btn' %> </p>
      </td>
      <td width="85%" align="center">
          <div id='container'></div>
      </td>
    </tr>
  </table>
            
    <% end %> 
  
 
       
  <p><%= I18n.t('materias.estudiantes.instruccion') %> </p>
  <%= p_datatable('tbl',columns: @subject_columns,datasource: @subjects,rowkey: 'id',caption: I18n.t('programas.materias.titulo') ,paginator: { rows: 20 },selectionMode: 'single' ) %>
  <p></p>
  <p align="center"><%= link_to I18n.t('programas.materias.volver'), list_program_path, :class => 'btn' %> </p>
  <% end %>
</ul>