config/routes.rb
Topclass::Application.routes.draw do

  get "semesters/new"
  get "semesters/index"
  get "semesters/show"

resources :users
resources :preregister_subjects
resources :sessions, only: [:new, :create, :destroy]
  
root  'sessions#new'
match '/newuser',  to: 'users#new',  via: 'get'
match '/help', to: 'static_pages#help', via: 'get'
match '/about',   to: 'static_pages#about',   via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/new_semester', to: 'new_semester#index', via: 'get'
  match '/new_semester_with_classes', to: 'new_semester#users_in_subject_rule', via: 'get'
  match '/new_semester_with_classes2', to: 'new_semester#users_not_in_subject_rule', via: 'get'
  
  match '/dashboard', to: 'dashboard#show', via: 'get'
  match '/dashboard_charts', to:'dashboard#load_charts', via: 'get' 
  match '/dashboard_notifications', to:'dashboard#notifications', via: 'get' 

  
  match '/forecast', to: 'forecasts#index', via: 'get'  
  match '/forecast_scenario', to: 'forecasts#show', via: 'get'  

resources :subjects
  match '/new_subject',  to: 'subjects#new',  via: 'get'
  match '/list_subject',  to: 'subjects#index',  via: 'get'
  match '/disable', to: 'subjects#disable', :as => 'disable', via: 'get'
  match '/list_student_by', to: 'subjects#showStudentList#:id', via: 'get'
  match '/showStudentList', to: 'subjects#showStudentList', via: 'get'
  match '/config_quota_by', to: 'subjects#goQuotaConfig#:id', via: 'get'
  match '/createQuota', to: 'subjects#createQuota', via: 'post'
  match '/searchStudentList', to: 'subjects#searchStudentList', via: 'get'
  
 
  resources :programs
  match '/list_registered', to: 'programs#showSubjectList#id', via: 'get'
  match '/list_program',  to: 'programs#index',  via: 'get'
  match '/searchSubjectList', to: 'programs#searchSubjectList', via: 'get'
  
  resources :teacher_subjects
  match '/new_teachersubjects',  to: 'teacher_subjects#new',  via: 'get'
  match '/list_teacher_subjects',  to: 'teacher_subjects#index',  via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  validates :firstname,  presence: true, length: { maximum: 100 }
  validates :lastname, presence: true, length: { maximum: 100 }
  validates :identificationtype, presence: true
  validates :identification, presence: true, length: { maximum: 20 }
  validates :status, presence: true
  validates :usertype, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  
  has_secure_password
  
  def admin?
    self.usertype == "Coordinador"
  end 
  
  has_many :user_programs
  has_many :programs, :through => :user_programs
  
  has_many :teacher_subjects
  has_many :subjects, :through => :teacher_subjects
  
  
  has_many :subject_records, :class_name => 'SubjectRecord', :foreign_key => 'user_student_id'
  has_many :preregister_subjects
  
  has_one :program
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #before_action :signed_in_user #, only: [:edit, :update, :create]
  #before_action :correct_user,   only: [:edit, :update]
  
  def show
    if !params[:disable].nil?
      if params[:disable] == "1"
         @user = User.find(params[:id])
         @user.update_attribute(:status, "Inactivo")
         flash[:success] = I18n.t('usuario.deshabilitado') 
      else
         @user = User.find(params[:id])
         @user.update_attribute(:status, "Activo")
         flash[:success] = I18n.t('usuario.habilitado')
      end
    else 
      
      @user = User.find(params[:id])
      @program = Program.find_by_id(params[:program_id])
      @programs = @user.programs.paginate(page: params[:page], :per_page => 3)
      @subject_records = @user.subject_records.paginate(page: params[:page])
      @preregister_subjects = @user.preregister_subjects.where(program_id: params[:program_id]).paginate(page: params[:page])
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      
              # Tell the UserMailer to send a welcome Email after save
        UserMailer.welcome_email(@user).deliver
       
      
          params[:programs].each do |program|
            user_programs = UserProgram.new(program_id: program, user_id: @user.id, status: "Activo")
            if user_programs.valid?
              user_programs.save
            else
              flash.now[:error] = 'Cant save user program'
              #@errors += user_programs.errors
            end 
        end
      
      
      flash[:success] = I18n.t('usuario.crear.exito') 
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])   
    @programs = @user.programs
    @programs_ids=Array.new(@programs.count)
    @programs.each do |program|
      @programs_ids.push(program.id)
    end
  end
  
  def update
      @user = User.find(params[:id])  
      if @user.update_attributes(user_params)
        
            params[:programs].each do |program|
            user_programs = UserProgram.new(program_id: program, user_id: @user.id, status: "Activo")
            if user_programs.valid?
              user_programs.save
            else
              flash.now[:error] = 'Cant save user program'
              #@errors += user_programs.errors
            end 
        end
        flash[:success] = "Info updated"
        sign_in @user
        redirect_to @user
      else
        render 'edit'
      end
  end
  
  def index
    @users = User.paginate(page: params[:page]).per_page(10)
  end
  
 def destroy
    User.find(params[:id]).destroy
    flash[:success] = I18n.t('usuario.eliminado') 
    redirect_to users_url
  end
  
  private

    def user_params
      params.require(:user).permit(:firstname,:lastname,:code,:identificationtype,:identification,:status,:usertype, :email, 
      :password,:password_confirmation)
      #params.require(:user).permit!
    end
    
        # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Por favor ingrese."
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    

end

app/helpers/users_helper.rb
module UsersHelper
  
  
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.firstname+" "+user.lastname, class: "gravatar")
  end

end

app/views/users/_user.html.erb
<li>
<%#= I18n.locale = :es %>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.firstname+" "+user.lastname, user %>
  <% if current_user.admin? %>
    <%= user.usertype %>
  <% end %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to I18n.t('delete'), user, method: :delete,
      data: { confirm: I18n.t('seguro') } %>
    <% if user.status == "Activo" %>
      | <%= link_to I18n.t('disable'), user_path(user,:disable => 1),
        data: { confirm: I18n.t('seguro') } %>
    <% end %>
    <% if user.status == "Inactivo" %>
      | <%= link_to I18n.t('enable'), user_path(user,:disable => 0),
        data: { confirm: I18n.t('seguro') } %>
    <% end %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Editar usuario") %>
<h1>Edit User</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :firstname, "Nombre" %>
      <%= f.text_field :firstname%>

      <%= f.label :lastname, "Apellidos" %>
      <%= f.text_field :lastname %>

      <%= f.label :code,"Código" %>
      <%= f.text_field :code %>

      <%= f.label :identificationtype, "Tipo de identificación" %>
      <%=f.select(:identificationtype,options_for_select([["CC", "CC"], ["CE", "CE"], ["TI", "TI"]]))%>       

      <%= f.label :identification, "Número de identificación" %>
      <%= f.text_field :identification %>

      <%= f.label :status, "Estado" %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   

      <%= f.label :usertype,"Tipo de usuario" %>
      <%=f.select(:usertype,options_for_select([["Estudiante", "Estudiante"], ["Coordinador", "Coordinador"], ["Profesor", "Profesor"]]))%>   

      <%= f.label :email, "Correo" %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmación" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :programs, "Programas" %>
      <%= select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name',  {selected: @programs_ids,disabled: @programs_ids}), :multiple => true %>

      <%= f.submit "Guardar cambios", class: "btn btn-large btn-primary" %>
      <% end %>
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">Cambiar</a>
    </div>
  </div>

app/views/users/index.html.erb
<% provide(:title, 'Todos los usuarios') %>
<h1>Todos los usuarios</h1>
<%= will_paginate   %>
<ul class="users">
  <% if current_user.usertype.eql?("Coordinador") %>
    <li><%= link_to "Nuevo usuario", newuser_path %></li>
  <% end %>
  <%= render @users %>
</ul>
<%= will_paginate  %>

app/views/users/new.html.erb
<% provide(:title, 'Create User') %>
<script type="text/javascript">
  $('select').change(validarProgramas);

  function validarProgramas(userT) {
<%#= if userT.eql?("Coordinador") %>
  <%#=  select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name'), :multiple => false %>

<%#=  else %>
  <%#=    select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name'), :multiple => true %>
<%# end %>
  }
</script>
<h1>Create User</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :firstname %>
      <%= f.text_field :firstname %>

      <%= f.label :lastname %>
      <%= f.text_field :lastname %>

      <%= f.label :code %>
      <%= f.text_field :code %>

      <%= f.label :identificationtype, "Identification Type" %>
      <%=f.select(:identificationtype,options_for_select([["CC", "CC"], ["CE", "CE"]]))%>       

      <%= f.label :identification %>
      <%= f.text_field :identification %>

      <%= f.label :status %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   

      <%= f.label :usertype,"User Type" %>
      <%=f.select(:usertype,options_for_select([["Estudiante", "Estudiante"], ["Coordinador", "Coordinador"], ["Profesor", "Profesor"]]))%>   
      <%#= select_ tag :usertype,options_for_select([["Estudiante", "Estudiante"], ["Coordinador", "Coordinador"], ["Profesor", "Profesor"]]),:multiple => false, :onchange=> "validarProgramas();" %>   

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>


      <%= f.label :programs %>

      <%= select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name'), :multiple => (if :usertype then true else"Estudiante".eql?"Estudiante" end) %>



      <%= f.submit "Create user", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.firstname+" "+@user.lastname) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user, size: 52  %>
        <%= @user.firstname %> <%= @user.lastname %>
      </h1>

      <%= @user.code %>, <%= @user.identificationtype %>, <%= @user.identification %>, <%= @user.status %>, <%= @user.usertype %>, <%= @user.email %>
    </section>
  </aside>
  <div class="span8">
    <% if @user.programs.any? %>
      <h3>Programs</h3>
      <ol class="programs">
        <%= render @programs %>
      </ol>
      <%= will_paginate @programs %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span8">

    <% if @user.preregister_subjects.any? %>
      <% if @user.usertype.eql?("Estudiante") && !@program.nil?%>
        <h3><%=I18n.t('usuario.preregistro')+" "+@program.name %></h3>
     <%= link_to "delete all", preregister_subject_path(:all => 1,:user_id =>@user.id,:program_id =>@program.id), method: :delete,
                                  data: { confirm: "You sure?" } %>
      <ol class="programs">
        <%= render @preregister_subjects %>
      </ol>
      <%= will_paginate @preregister_subjects %>
    <% end %>
    <% end %>
  </div>
</div>
