config/routes.rb
Topclass::Application.routes.draw do

  get "semesters/new"
  get "semesters/index"
  get "semesters/show"

resources :users
resources :preregister_subjects
resources :sessions, only: [:new, :create, :destroy]
  
root  'sessions#new'
match '/newuser',  to: 'users#new',  via: 'get'
match '/help', to: 'static_pages#help', via: 'get'
match '/about',   to: 'static_pages#about',   via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/new_semester', to: 'new_semester#index', via: 'get'
  match '/new_semester_with_classes', to: 'new_semester#users_in_subject_rule', via: 'get'
  match '/new_semester_with_classes2', to: 'new_semester#users_not_in_subject_rule', via: 'get'
  
  match '/dashboard', to: 'dashboard#show', via: 'get'
  match '/dashboard_charts', to:'dashboard#load_charts', via: 'get' 
  match '/dashboard_notifications', to:'dashboard#notifications', via: 'get' 

  
  match '/forecast', to: 'forecasts#index', via: 'get'  
  match '/forecast_scenario', to: 'forecasts#show', via: 'get'  

resources :subjects
  match '/new_subject',  to: 'subjects#new',  via: 'get'
  match '/list_subject',  to: 'subjects#index',  via: 'get'
  match '/disable', to: 'subjects#disable', :as => 'disable', via: 'get'
  match '/list_student_by', to: 'subjects#showStudentList#:id', via: 'get'
  match '/showStudentList', to: 'subjects#showStudentList', via: 'get'
  match '/config_quota_by', to: 'subjects#goQuotaConfig#:id', via: 'get'
  match '/createQuota', to: 'subjects#createQuota', via: 'post'
  match '/searchStudentList', to: 'subjects#searchStudentList', via: 'get'
  
 
  resources :programs
  match '/list_registered', to: 'programs#showSubjectList#id', via: 'get'
  match '/list_program',  to: 'programs#index',  via: 'get'
  match '/searchSubjectList', to: 'programs#searchSubjectList', via: 'get'
  
  resources :teacher_subjects
  match '/new_teachersubjects',  to: 'teacher_subjects#new',  via: 'get'
  match '/list_teacher_subjects',  to: 'teacher_subjects#index',  via: 'get'

  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  before_save { self.code = code.upcase }
   
  validates :name, presence: true, length: { maximum: 200 }
  validates :code, presence: true, length: { maximum: 100 },  uniqueness: { case_sensitive: false }
  validates :quota, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :credits, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :status, presence: true
  
  has_many :teacher_subjects
  has_many :users, :through => :teacher_subjects
  
  has_many :subject_semesters
  has_many :semesters , :through => :subject_semesters
  
  has_many :subject_programs
  has_many :programs, :through => :subject_programs
  
  has_one :quota_config
  
  has_many :preregister_subjects
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index   
    @subjects = Subject.paginate(page: params[:page])
  end
  
  def show
    @subject = Subject.find(params[:id])
    if @subject.status == "true" 
      flash[:success] = "Subject enable"
    else
      flash[:fail] = "Subject disabled"
    end
  end
  
  def showStudentList
    # <%= link_to I18n.t('materias.boton.estudiantes'), :controller => 'subjects', :action => 'showStudentList', :idSubject => subject.id %>
    @subject = Subject.find(params[:format])
    @semester = Semester.new
    @student_columns = [   {field: 'idStudent', headerText: 'ID', sortable: true}, {field: 'identification', headerText: I18n.t('materias.estudiantes.table.identificacion'), sortable: true},    
      {field: 'firstname', headerText: I18n.t('materias.estudiantes.table.nombre'), sortable: true},   {field: 'lastname', headerText: I18n.t('materias.estudiantes.table.apellido'), sortable: true},   
      {field: 'email', headerText: I18n.t('materias.estudiantes.table.email'), sortable: true}, {field: 'status', headerText: I18n.t('materias.estudiantes.table.estado'), sortable: true}                  
                        ] 
    @semester = Semester.last
    @students = Subject.find_by_sql(["select distinct  u.id idStudent, u.firstname, u.lastname, u.identification, u.email, u.status from preregister_subjects sr, users u where sr.semester_id = ? and sr.subject_id = ? and sr.user_id = u.id ", @semester.id, @subject.id])
    @semester.status =  @subject.id
    @students.count
  end
  
  def searchStudentList
    @subject = Subject.find_by_id(params[:semester][:status])
    @semester = Semester.find(params[:semester][:id])
    @student_columns = [   {field: 'idStudent', headerText: 'ID', sortable: true}, {field: 'identification', headerText: I18n.t('materias.estudiantes.table.identificacion'), sortable: true},    
      {field: 'firstname', headerText: I18n.t('materias.estudiantes.table.nombre'), sortable: true},   {field: 'lastname', headerText: I18n.t('materias.estudiantes.table.apellido'), sortable: true},   
      {field: 'email', headerText: I18n.t('materias.estudiantes.table.email'), sortable: true}, {field: 'status', headerText: I18n.t('materias.estudiantes.table.estado'), sortable: true}                  
                        ] 
    @students = Subject.find_by_sql(["select distinct  u.id idStudent, u.firstname, u.lastname, u.identification, u.email, u.status from preregister_subjects sr, users u where sr.semester_id = ? and sr.subject_id = ? and sr.user_id = u.id ", @semester.id, @subject.id])
    @semester.status =  @subject.id
    flash[:success] = "Se ha cargado el listado de usuario para el semestre " + @semester.name   
    render "showStudentList"
  end
  
  def goQuotaConfig
    @subject = Subject.find(params[:format])
    @quota =  QuotaConfig.where("subject_id = ?", @subject.id).last
    if @quota.nil?
      @quota = QuotaConfig.new
    end
    @quota.subject_id = @subject.id
  end
  
  def createQuota
    begin
       @quota =  QuotaConfig.find(params[:quota_config][:id])
       if @quota.own_quota < (@quota.pregrade_quota + @quota.program_quota)
         flash[:fail] = "La cuota máxima no debe superar la suma de pregado y postgrado"
         render "goQuotaConfig"
       else
         logger.info("INFO: Update quota config ")
         @quota.update_attributes(params[:quota_config])
         flash[:success] = "Quota was updated sucesfull"         
         redirect_to subjects_path    
       end
    rescue
      @quota = QuotaConfig.new(quota_params)
      if @quota.own_quota < (@quota.pregrade_quota + @quota.program_quota)
        flash[:fail] = "La cuota máxima no debe superar la suma de pregado y postgrado"
         render "goQuotaConfig"
       else
         logger.info("INFO: Saving new quota config ")
         @quota.save
         flash[:success] = "Quota was created sucesfull"
      end
    end           
  end
  
  def new
    @subject = Subject.new
  end
  
  def create
    @subject = Subject.new(subject_params)    
    if @subject.save  
      flash[:success] = "Subject created sucesfull"
      redirect_to subjects_path
    else
      flash[:fail] = "Fail Subject creation"
      render "new"
    end
  end
  
  def edit
     @subject = Subject.find(params[:id])
  end
  
  def disable
    @subject = Subject.find(params[:format])
    @subject.status = @subject.status == "Inactivo" ? "Activo" : "Inactivo"
    if @subject.update_attributes(params[:subject])
      flash[:success] = @subject.status == "Inactivo" ?  "La materia fue Inactivada" : "La materia fue Activada"
       redirect_to subjects_path
    else
      flash[:fail] = "Fail disable Subject"
      render "index"
    end
  end
  
  def update
    @subject = Subject.find_by_id(params[:id])
    if @subject.update_attributes(params[:subject])
      flash[:success] = "Subject was updated"
        redirect_to subjects_path
      else
        render "edit"
      end
  end
  
  def destroy
    @subject = Subject.find_by_id(params[:id])
    if @subject.destroy
      flash[:success] = "Subject was destroyed." 
      redirect_to subjects_path
    else
      flash[:fail] = "Fail delete Subject"
      render "index"
    end
  end
  
    private

  def subject_params
      params.require(:subject).permit(:code,:name,:quota,:credits,:status) 
    end
  
    def quota_params
      params.require(:quota_config).permit(:subject_id,:own_quota,:program_quota,:pregrade_quota) 
    end
  
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/edit.html.erb
<% provide(:title, 'Edit Subject') %>
<h1>Edit Subject</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@subject) do |f| %>
     <%= render 'shared/subject_error_messages' %>

      <%= f.label :code %>
      <%= f.text_field :code %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :quota %>
      <%= f.text_field :quota %>
      
      <%= f.label :credits %>
      <%= f.text_field :credits %>
      
      <%= f.label :status %>
       <%=f.select(:status,options_for_select([["Activo", "activo"], ["Inactivo", "inactivo"]], 2) )%>   
            
  <p align="center">
      <%= f.submit "Update subject", class: "btn btn-primary" %> 
     <%= link_to "Go Back", list_subject_path, class: "btn" %> 
    </p> 
    <% end %>
  </div>
</div>

app/views/subjects/goQuotaConfig.html.erb
<% provide(:title, 'Configurar cuotas de asignación de cupos') %>
<h1>Configurar cuotas de asignación de cupos</h1>
<div class="row">
  <div class="span6 offset3">   

    <%= form_for @quota, url: createQuota_path(@quota) , html: {method: "post"} do |f|  %>
   <%= render 'shared/quota_error_messages' %>
    <%= p_fieldset('default',legend: 'Datos Básicos',style: 'margin-bottom:10px') do %>      
      <%= f.hidden_field :id  %>  
      <%= f.hidden_field :subject_id %>
      
      <%= f.label :own_quota , "Cuota total materia"%>
      <%= f.text_field :own_quota %>
      
      <%= f.label :program_quota , "Cuota materia" %>
      <%= f.text_field :program_quota %>
      
      <%= f.label :pregrade_quota, "Cuota pregrado" %>
      <%= f.text_field :pregrade_quota %>
     
    <% end %> 
    
    <p align="center">
      <%= f.submit "Cambiar cuota", class: "btn btn-primary" %> 
     <%= link_to "Volver", list_subject_path, class: "btn" %> 
    </p> 
      
    <% end %>
  </div>
</div>

app/views/subjects/index.html.erb
<% provide(:title, 'All subjects') %>
<h1>Materias</h1>
<p align="center"><%= link_to "Nueva Materia", new_subject_path, :class => 'btn btn-primary'  %></p> 

<%= will_paginate %>
<ul class="subjects">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Cuota</th>
      <th>Creditos</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.id %></td>
          <td><%= subject.code %></td>
        <td><%= link_to subject.name, subject_path(subject) %></td>
          <td><%= subject.quota %></td>
          <td><%= subject.credits %></td>
        <td>
          
          <%= link_to I18n.t('materias.boton.estudiantes'), list_student_by_path(subject.id), :class => 'btn btn-mini' %>
           <%= link_to I18n.t('materias.boton.quota'), config_quota_by_path(subject.id), :class => 'btn btn-mini' %>
          <%= link_to 'Editar', edit_subject_path(subject), :class => 'btn btn-mini' %>
          <%= link_to subject.status == "Activo" ? 'Deshabilitar' : 'Habilitar', disable_path(subject.id), :class => 'btn btn-mini' %>
          <%= link_to 'Borrar', subject_path(subject), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          
  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</ul>
<%= will_paginate %>
<p align="center"><%= link_to "Nueva Materia", new_subject_path, :class => 'btn btn-primary'  %></p>

app/views/subjects/new.html.erb
<% provide(:title, 'Create Subject') %>
<h1>Crear Materia</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@subject) do |f| %>
     <%= render 'shared/subject_error_messages' %>

    <%= p_fieldset('default',legend: 'Datos Básicos',style: 'margin-bottom:10px') do %>      
    
      <%= f.label :code, "Codigo" %>
      <%= f.text_field :code %>
      
      <%= f.label :name , "Nombre"%>
      <%= f.text_field :name %>
      
      <%= f.label :quota , "Cuota"%>
      <%= f.text_field :quota %>
      
      <%= f.label :credits, "Créditos"%>
      <%= f.text_field :credits %>
      
      <%= f.label :status , "Estado"%>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   
     
    <% end %> 
    
    <p align="center">
      <%= f.submit "Crear materia", class: "btn btn-primary" %> 
     <%= link_to "Volver", list_subject_path, class: "btn" %> 
    </p> 
      
    <% end %>
  </div>
</div>

app/views/subjects/show.html.erb
<% provide(:title, 'Show Subject') %>
<h1>Detail Subject</h1>

<div class="row">
  <div class="span6 offset3">
       
<%= form_for(@subject) do |f| %>
      <%= f.label :code %> 
      <%= @subject.code %>
      
      <%= f.label :name %>
      <%= @subject.name %>
      
      <%= f.label :quota %>
     <%= @subject.quota %>
      
      <%= f.label :credits %>
      <%= @subject.credits %>
      
      <%= f.label :status %>
      <%= if @subject.status == "true" then "Activo" else "Inactivo" end %>
    <%end%>
  </div>
</div>
 <p align="center"><%= link_to "Atrás", list_subject_path, :class => 'btn' %> </p>

app/views/subjects/showStudentList.html.erb
 <script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
      google.load('visualization', '1', {packages:['gauge']});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Inscritos', <%= @students.count %>]
        ]);

        var options = {
          width: 400, height: 120,
          redFrom: <%= @subject.quota - 10%> , redTo: <%= @subject.quota %>,
          yellowFrom:<%= @subject.quota / 2 %>, yellowTo: <%= @subject.quota - 10 %>,
          minorTicks: 5, max : <%= @subject.quota %>, greenFrom: 0, greenTo: <%= @subject.quota / 2 %>
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>

<% provide(:title, 'Todas las materias por programa') %>

<h1><%= I18n.t('materias.estudiantes.titulo') %></h1>

<ul class="students">
  <%= p_fieldset('default',legend: I18n.t('materias.estudiantes.subtitulo'),style: 'margin-bottom:10px') do %>
  
     <%= form_for @semester, url: searchStudentList_path(@semester) , html: {method: "get"} do |f|  %>
  
  <table>
    <tr>
       <td width="50%" align="center">
          <div id='chart_div'></div>
      </td>
      <td width="50%">
        <%= f.hidden_field :status %>
      <%= f.label :id , "Semestre"%>
  
      <% semester_array = Semester.all.map { |sem| [sem.name, sem.id] } %>
  
      <%=f.select(:id,options_for_select(semester_array), :style => "width:70px")%>   
      <%= f.submit "Buscar", class: "btn btn-primary" %>
      </td>
    </tr>
  </table>
            
    <% end %>   
  
  <p align="center"><%= link_to I18n.t('materias.estudiantes.volver'), list_subject_path, :class => 'btn' %> </p>
  <p><%= I18n.t('materias.estudiantes.instruccion') %> </p>
  <p align="center">Se han encontrado un total de <%= @students.count %> estudiantes</p>
  <%= p_datatable('tbl',columns: @student_columns,datasource: @students,rowkey: 'id',caption: I18n.t('materias.estudiantes.titulo') ,paginator: { rows: 20 },selectionMode: 'single' ) %>
  <p></p>
  <p align="center"><%= link_to I18n.t('materias.estudiantes.volver'), list_subject_path, :class => 'btn' %> </p>
  <% end %>
</ul>